//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorrectRPMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RPMSEntities : DbContext
    {
        public RPMSEntities()
            : base("name=RPMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuditLog> AuditLog { get; set; }
        public virtual DbSet<tblSchoolDetails> tblSchoolDetails { get; set; }
        public virtual DbSet<tblUsers> tblUsers { get; set; }
        public virtual DbSet<tblFaculty> tblFaculty { get; set; }
        public virtual DbSet<tblFacultyType> tblFacultyType { get; set; }
        public virtual DbSet<tblFacultyTemp> tblFacultyTemp { get; set; }
        public virtual DbSet<tblDeptTemp> tblDeptTemp { get; set; }
        public virtual DbSet<tblMajor> tblMajor { get; set; }
        public virtual DbSet<tblCourses> tblCourses { get; set; }
        public virtual DbSet<tblCoursesTemp> tblCoursesTemp { get; set; }
        public virtual DbSet<tblMajorTemp> tblMajorTemp { get; set; }
        public virtual DbSet<tblGradingSystem> tblGradingSystem { get; set; }
        public virtual DbSet<tblGrading> tblGrading { get; set; }
        public virtual DbSet<tblLevel> tblLevel { get; set; }
        public virtual DbSet<tblNation> tblNation { get; set; }
        public virtual DbSet<tblState> tblState { get; set; }
        public virtual DbSet<tblLocalGovt> tblLocalGovt { get; set; }
        public virtual DbSet<tblMaritalStatus> tblMaritalStatus { get; set; }
        public virtual DbSet<tblSession> tblSession { get; set; }
        public virtual DbSet<tblStaffRank> tblStaffRank { get; set; }
        public virtual DbSet<tblPosition> tblPosition { get; set; }
        public virtual DbSet<tblSemester> tblSemester { get; set; }
        public virtual DbSet<tblSessionSemester> tblSessionSemester { get; set; }
        public virtual DbSet<tblRoles> tblRoles { get; set; }
        public virtual DbSet<tblUser> tblUser { get; set; }
        public virtual DbSet<tblConfig> tblConfig { get; set; }
        public virtual DbSet<tblStaffRole> tblStaffRole { get; set; }
        public virtual DbSet<tblAssignCoursesCoordinator> tblAssignCoursesCoordinator { get; set; }
        public virtual DbSet<tblSecurityQuestionList> tblSecurityQuestionList { get; set; }
        public virtual DbSet<tblUserSecurityAnswer> tblUserSecurityAnswer { get; set; }
        public virtual DbSet<tblStatus> tblStatus { get; set; }
        public virtual DbSet<tblStudentDisciplineLeave> tblStudentDisciplineLeave { get; set; }
        public virtual DbSet<tblStudentCourseExempt> tblStudentCourseExempt { get; set; }
        public virtual DbSet<tblAuditTray> tblAuditTray { get; set; }
        public virtual DbSet<tblDept> tblDept { get; set; }
    }
}
