//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorrectRPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConfig
    {
        public string Email { get; set; }
        public string Password { get; set; }
        public string EmailHost { get; set; }
        public int Port { get; set; }
        public bool EnableSSL { get; set; }
        public bool BodyHtml { get; set; }
        public int ConfigID { get; set; }
    }
}
