//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorrectRPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMajorTemp
    {
        public string FacultyName { get; set; }
        public string DepartmentName { get; set; }
        public string DepartmentCode { get; set; }
        public int DeptID { get; set; }
        public string MajorCode { get; set; }
        public string MajorName { get; set; }
        public string DegreeAwarded { get; set; }
    }
}
