//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorrectRPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSessionSemester
    {
        public int SessionSemesterID { get; set; }
        public string SessionSemester { get; set; }
        public string Session { get; set; }
        public string Semester { get; set; }
    }
}
