//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorrectRPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentDisciplineLeave
    {
        public int DiscLeaveID { get; set; }
        public string MatricNumber { get; set; }
        public string Status { get; set; }
        public string SessSemester { get; set; }
        public int Duration { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
    }
}
