//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorrectRPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblState
    {
        public int StateId { get; set; }
        public int NationId { get; set; }
        public string NationCode { get; set; }
        public string Statename { get; set; }
        public string NationName { get; set; }
    }
}
