//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorrectRPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int StaffID { get; set; }
        public string StaffNumber { get; set; }
        public string Title { get; set; }
        public string Surname { get; set; }
        public string FirstName { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public decimal Mobile { get; set; }
        public string Sex { get; set; }
        public string Department { get; set; }
        public string Role { get; set; }
        public string Password { get; set; }
        public bool UpdatePassword { get; set; }
        public string Faculty { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> LinkExpirationDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> LinkActivated { get; set; }
        public Nullable<bool> SecurityQueCreated { get; set; }
    }
}
