//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorrectRPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserSecurityAnswer
    {
        public int UserSecurityAnswer { get; set; }
        public string StaffNumber { get; set; }
        public string SecurityQue1 { get; set; }
        public string Answer1 { get; set; }
        public string SecurityQue2 { get; set; }
        public string Answer2 { get; set; }
        public string SecurityQue3 { get; set; }
        public string Answer3 { get; set; }
    }
}
